// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tyjigmsuzbtbdbowtdaz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5amlnbXN1emJ0YmRib3d0ZGF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMDA4NzcsImV4cCI6MjA2OTY3Njg3N30.8F_Y36sAtmKmcynHKs4lpP2pCC2d0CWQE6J_G2ixmi0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});