// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nizncftfnjoecldvnskt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5pem5jZnRmbmpvZWNsZHZuc2t0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5NzIwMjYsImV4cCI6MjA3MDU0ODAyNn0.I2vmW7_NWIrEB8LLd7gdyIU7XCRPmAbicmHxk06PAdU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});